apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: jaeger-oauth
    version: v1
  name: jaeger-oauth
  namespace: kube-monitor
data:
  oauth-proxy.cfg: |
    ## OAuth2 Proxy Config File
    ## https://github.com/oauth2-proxy/oauth2-proxy
    http_address = ":8080"
    reverse_proxy = true
    ## provider
    provider = "keycloak"
    client_id = "jaeger"
    client_secret = "{秘钥}"
    login_url = "https://keycloak.taozhang.net.cn/auth/realms/k8s-openid/protocol/openid-connect/auth"
    redeem_url = "https://keycloak.taozhang.net.cn/auth/realms/k8s-openid/protocol/openid-connect/token"
    validate_url = "https://keycloak.taozhang.net.cn/auth/realms/k8s-openid/protocol/openid-connect/userinfo"
    redirect_url = "https://jaeger.taozhang.net.cn/oauth2/callback"
    insecure_oidc_allow_unverified_email=true
    keycloak_group = "/managers"
    scope = "openid email profile offline_access"
    upstreams = [
         "http://jaeger-query:16686"
    ]
    cookie_secret = "{秘钥}"
    cookie_domains = [
      ".taozhang.net.cn"
    ]
    ## 可信email， 会与scope中的email对比。
    email_domains = [
      "*"
    ]
    pass_user_headers = true
    pass_access_token = true
    pass_authorization_header = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-oauth
  namespace: kube-monitor
  labels:
    k8s-app: jaeger-oauth
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: jaeger-oauth
      version: v1
  template:
    metadata:
      labels:
        k8s-app: jaeger-oauth
        version: v1
    spec:
      containers:
        - name: jaeger-oauth
          image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
          command: ["/bin/oauth2-proxy"]
          args:
          - --config=/etc/oauth-proxy.cfg
          volumeMounts:
            - mountPath: /etc/oauth-proxy.cfg
              name: conf
              subPath: oauth-proxy.cfg  
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
      volumes:
        - name: conf
          configMap:
            name: jaeger-oauth
            items:
            - key: oauth-proxy.cfg
              path: oauth-proxy.cfg
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-oauth-query
  namespace: kube-monitor
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    k8s-app: jaeger-oauth
    version: v1