version: '3'
services:
  mybooks:
    image: my-books:v2
    container_name: books
    restart: always
    networks:
      - books
    ports:
      - 33000:3000
      - 5729:35729
    volumes:
      - ./../:/data/docsify
networks:
  books: