apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.operator-sdk/verbosity: "1"
spec:
  auth:
    strategy: openid
    openid:
      client_id: "kiali"
      issuer_uri: "https://keycloak.taozhang.net.cn/auth/realms/k8s-openid"
      authentication_timeout: 300
      insecure_skip_verify_tls: true
      scopes: ["openid", "profile", "email"]
      disable_rbac: true
  external_services:
    custom_dashboards:
      enabled: true
    tracing:
      enabled: true
      url: https://jaeger.taozhang.net.cn
      in_cluster_url: http://jaeger-query.kube-monitor:16686
    prometheus:
      url: http://thanos-querier.kube-monitor:9090
  server:
    web_schema: https
    web_port: 443
  api:
    namespaces: 
      exclude:
      - "kube-system"
      - "rook-ceph"
      - "metallb-system"
      - "local-path-storage"
      - "istio-system"